[WIP] Here we go, mlc for scheduled markdown link checking with optional issue creation.

diff --git a/.github/workflows/workflow-validate-repo-markdown.yml b/.github/workflows/workflow-validate-repo-markdown.yml
--- a/.github/workflows/workflow-validate-repo-markdown.yml
+++ b/.github/workflows/workflow-validate-repo-markdown.yml
@@ -11,7 +11,11 @@ on:
         description: 'the path to the markdown link check config file'
         required: false
         default: 'build/config/.markdown-link-check/config.json'
-        type: string
+        type: 
+      createIssue:
+        description: 'determines if reports of broken links open a new GitHub issue'
+        required: false
+        default: false
   workflow_dispatch:
     inputs:
       ignorePattern:
@@ -24,6 +28,10 @@ on:
         required: false
         default: 'build/config/.markdown-link-check/config.json'
         type: string
+      createIssue:
+        description: 'determines if reports of broken links open a new GitHub issue'
+        required: false
+        default: false
 jobs:
   validate-repo-markdown:
     name: Validate Repo Markdown
@@ -33,6 +41,17 @@ jobs:
     - uses: actions/checkout@v3 # current: dcd71f646680f2efd8db4afa5ad64fdcba30e748
       with:
         submodules: recursive
+    # Variable setup needed to support workflow_call and workflow_Dispath, but the
+    # cron job has no access to these context inputs. So we work around that with
+    # defaults or interactive values bound to env vars.
+    - name: Set up env (enable issue creation)
+      if: github.event.inputs.createIssue == true || inputs.createIssue == 'true'
+      run: |
+        echo CREATE_ISSUE=true >> $GITHUB_ENV
+    - name: Set up env (disable issue creation)
+      if: github.event.inputs.createIssue == false && inputs.createIssue == 'false'
+      run: |
+        echo CREATE_ISSUE=false >> $GITHUB_ENV
     # Setup runtime environment
     # -------------------------
     - name: Set up NodeJS
@@ -59,4 +78,16 @@ jobs:
     - name: Validate repo Markdown content instances
       run: |
         # this command will filter out any docs Markdown files, which are checked in a different job
-        git ls-files "*/*.md" -z | grep --null-data -v "${{ inputs.ignorePattern }}" | xargs -0 markdown-link-check -q -c "${{ inputs.markdownLinkCheckConfig }}"
+        git ls-files "*/*.md" -z | grep --null-data -v "${{ inputs.ignorePattern }}" | xargs -0 markdown-link-check -c "${{ inputs.markdownLinkCheckConfig }}" | tee mlc_report.log
+        # PIPESTATUS is a 0 index array of exit codes in a pipe, 2 is xargs mlc exec and 3 is the tee command
+        result_code=${PIPESTATUS[2]}
+        echo "::set-output name=mlc_report::$(cat mlc_report.log)"
+        exit $result_code
+      id: linkchecker
+    - name: Create issue if bad links detected
+      if: steps.linkchecker.outputs.exit_code != 0 && env.CREATE_ISSUE
+      uses: peter-evans/create-issue-from-file@97e6f902a416aac38834e23fa52e166aad0437d2 # v3.0.0
+      with:
+        title: Link Checker Report
+        content-filepath: mlc_report.log
+        labels: bug
